model:
  _name_: dna_embedding
  d_model: 512
  n_layer: 2
  d_inner: 2048
  vocab_size: 12
  resid_dropout: 0.0
  embed_dropout: 0.1
  fused_mlp: False # figure out how to use fused MLP, maybe only with bf16 + a100
  fused_dropout_add_ln: False
  residual_in_fp32: True
  pad_vocab_size_multiple: 8
  checkpoint_mixer: True
  checkpoint_mlp: True
  layer:
    _name_: hyena
    emb_dim: 5
    filter_order: 64
    short_filter_order: 3
    l_max: 232  # required to be set the same as the pretrained model if using, don't forget the +2!  ${eval:${dataset.max_length}+2}
    modulate: True
    w: 10
    lr: ${optimizer.lr}
    wd: 0.0
    lr_pos_emb: 0.0
    bidirectional: False
train:
  d_output: 1  # number of classes

dataset:
  dataset_name: 'apoa1'
  dest_path: null
  val_only: True
  #fasta_file: '/data/code/hyena-dna/data/hg38/hg38.ml.fa'
  max_length: 230
  d_output: 1
  use_padding: True
  padding_side: 'left'
  add_eos: False
  batch_size: 128