_name_: mpra_agarwal_seq
dataset_name: hepg2
dest_path: null
kfold: None
max_length: 1024
d_output: 1
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
k562:
  train_len: 169672
hepg2:
  train_len: 104874