_name_: mpra_agarwal
dataset_name: hepg2
dest_path: null
fasta_file: '/data/code/hyena-dna/data/hg38/hg38.ml.fa'
max_length: 1024
d_output: 1
use_padding: True
padding_side: 'left'
add_eos: False
batch_size: 32
train_len: ${.${.dataset_name}.train_len}
__l_max: ${.max_length}
shuffle: true  # set this as default!
# these are used to find the right attributes automatically for each dataset
k562:
  train_len: 84822
hepg2:
  train_len: 53974